#!/bin/bash

echo "🎬 App Preview Recording Guide"
echo "=============================="
echo ""
echo "📱 iPhone Screen Recording Setup:"
echo "1. Open Settings → Control Center"
echo "2. Add 'Screen Recording' to Control Center"
echo "3. Open your app via Expo Go"
echo "4. Swipe down from top-right to open Control Center"
echo "5. Tap Screen Recording button (circle icon)"
echo "6. Start recording and follow the scripts below"
echo ""

echo "🎯 Recording Tips:"
echo "• Keep each video 15-30 seconds"
echo "• Record in portrait mode only"
echo "• Move slowly and deliberately"
echo "• Pause 1-2 seconds on each screen"
echo "• Don't talk during recording"
echo ""

echo "📝 Video Scripts:"
echo ""
echo "🎬 Preview 1: App Overview (15-20s)"
echo "1. Start on home screen (3s)"
echo "2. Show quote animation (3s)"
echo "3. Scroll to feature cards (4s)"
echo "4. Highlight key features (4s)"
echo "5. Return to title (3s)"
echo ""

echo "🎬 Preview 2: Criminal Database (20-25s)"
echo "1. Tap 'Access Criminal Database' (2s)"
echo "2. Show criminal list (4s)"
echo "3. Tap Reddington profile (1s)"
echo "4. Show detailed popup (5s)"
echo "5. Show status badges (4s)"
echo "6. Close and return (3s)"
echo ""

echo "🎬 Preview 3: Edit Features (20-25s)"
echo "1. From criminal list (1s)"
echo "2. Tap 'Add New Criminal' (1s)"
echo "3. Show edit form (4s)"
echo "4. Fill in name/aliases (4s)"
echo "5. Select status options (4s)"
echo "6. Select threat level (4s)"
echo "7. Tap Save (2s)"
echo ""

echo "💾 After Recording:"
echo "1. Videos save to Photos app"
echo "2. Transfer to Mac via AirDrop"
echo "3. No editing needed - use raw recordings"
echo "4. Upload directly to App Store Connect"
echo ""

echo "🎵 Optional: Add Background Music"
echo "• Use GarageBand or iMovie"
echo "• Keep volume low"
echo "• Use dramatic/suspenseful music fitting FBI theme"
echo "• Export in same resolution as original"