#!/bin/bash

echo "🎬 iPhone Mirroring + QuickTime Recording Guide"
echo "=============================================="
echo ""
echo "📱 Setup iPhone Mirroring:"
echo "1. Open 'iPhone Mirroring' app on Mac"
echo "2. Connect your iPhone (follow prompts)"
echo "3. Open Expo Go on mirrored iPhone"
echo "4. Load your Blacklist app"
echo ""

echo "🎥 Record with QuickTime:"
echo "1. Open QuickTime Player on Mac"
echo "2. File → New Screen Recording"
echo "3. Click dropdown arrow next to record button"
echo "4. Select 'iPhone Mirroring' window as source"
echo "5. Click Record button"
echo "6. Click on iPhone Mirroring window to start"
echo ""

echo "📹 Recording Each Preview:"
echo ""
echo "🎬 Preview 1: App Overview (15-20s)"
echo "• Start recording"
echo "• Show home screen with animations (4s)"
echo "• Scroll to feature cards (4s)"  
echo "• Highlight key features (4s)"
echo "• Return to title (4s)"
echo "• Stop recording (Cmd+Ctrl+Esc)"
echo ""

echo "🎬 Preview 2: Criminal Database (20-25s)"
echo "• Start new recording"
echo "• Tap 'Access Criminal Database' (3s)"
echo "• Show criminal list (4s)"
echo "• Tap Reddington profile (2s)"
echo "• Show detailed popup (6s)"
echo "• Show status/threat badges (4s)"
echo "• Close popup (3s)"
echo "• Stop recording"
echo ""

echo "🎬 Preview 3: Edit Features (20-25s)"
echo "• Start new recording"
echo "• Tap 'Add New Criminal' (2s)"
echo "• Show edit form fields (4s)"
echo "• Fill in name field (3s)"
echo "• Show aliases field (3s)"
echo "• Select status options (4s)"
echo "• Select threat level (4s)"
echo "• Tap Save button (2s)"
echo "• Stop recording"
echo ""

echo "💾 File Management:"
echo "• Recordings save as .mov files on Desktop"
echo "• Perfect format for App Store Connect"
echo "• No additional editing needed"
echo "• Upload directly to App Store Connect"
echo ""

echo "🎯 Pro Tips:"
echo "• Use Cmd+Ctrl+Esc to stop recording"
echo "• Record multiple takes for each preview"
echo "• Move cursor slowly and deliberately"
echo "• Pause 1-2 seconds between actions"
echo "• Keep recordings under 30 seconds each"
echo ""

echo "📐 Resolution:"
echo "• iPhone Mirroring maintains native resolution"
echo "• Perfect for App Store requirements"
echo "• No need to resize like screenshots"