// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZdTdbKtxKjlAHb4QSyb74p-Zbl4Dcy00',
    appId: '1:256384605236:web:fccda3bb0b38ce4afbbe61',
    messagingSenderId: '256384605236',
    projectId: 'blacklist-9bdf6',
    authDomain: 'blacklist-9bdf6.firebaseapp.com',
    storageBucket: 'blacklist-9bdf6.firebasestorage.app',
    measurementId: 'G-DWZ40L58TS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr9lqBHNwTeV_ysVEDsVhKUCKvCqYeO7I',
    appId: '1:256384605236:android:41dfd33f346059fdfbbe61',
    messagingSenderId: '256384605236',
    projectId: 'blacklist-9bdf6',
    storageBucket: 'blacklist-9bdf6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOu8I02MtomfNPOXC-ixlIdFzcA3sqEPQ',
    appId: '1:256384605236:ios:c6bbbe70ddf75fd7fbbe61',
    messagingSenderId: '256384605236',
    projectId: 'blacklist-9bdf6',
    storageBucket: 'blacklist-9bdf6.firebasestorage.app',
    iosBundleId: 'com.example.crimsondossier',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOu8I02MtomfNPOXC-ixlIdFzcA3sqEPQ',
    appId: '1:256384605236:ios:c6bbbe70ddf75fd7fbbe61',
    messagingSenderId: '256384605236',
    projectId: 'blacklist-9bdf6',
    storageBucket: 'blacklist-9bdf6.firebasestorage.app',
    iosBundleId: 'com.example.crimsondossier',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZdTdbKtxKjlAHb4QSyb74p-Zbl4Dcy00',
    appId: '1:256384605236:web:d6aec12ffa0d13b2fbbe61',
    messagingSenderId: '256384605236',
    projectId: 'blacklist-9bdf6',
    authDomain: 'blacklist-9bdf6.firebaseapp.com',
    storageBucket: 'blacklist-9bdf6.firebasestorage.app',
    measurementId: 'G-EPXWW6LRLP',
  );

}